apiVersion: apps/v1
kind: Deployment
metadata:
  name: "bootstrap"
spec:
  selector:
    matchLabels:
      app: "bootstrap"
  template:
    metadata:
      labels:
        app: "bootstrap"
    spec:
      containers:
        - name: "bootstrap"
          image: "micronautsample:latest"#todo change this to the real registry
          imagePullPolicy: Never #change this for production. I added since we are getting the image from local machine
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "bootstrap"
spec:
  selector:
    app: "bootstrap"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
